#!/usr/bin/env python3
"""Generate M01-style lesson markdown for M14–M17 (Agenda Ops thread)."""
from __future__ import annotations

from generate_m10_m13_lessons import _lesson, write_materia

PROJ14 = "projects/m14-patrones"
PROJ15 = "projects/m15-calidad"
PROJ16 = "projects/m16-ihc"
PROJ17 = "projects/m17-agenda-ops"

M14 = [
    _lesson(
        "Entorno M14 y Strategy de precios",
        1,
        "Refactoring.Guru Factory + Strategy (ES)",
        f"{PROJ14}/src/precio-strategy.ts + adr/001",
        "Preparar `projects/m14-patrones/` e implementar **Strategy** para precio de servicio (base vs promoción) con tests.",
        "Los precios en Agenda Ops cambiarán; Strategy evita `if (promo)` esparcidos.",
        ["Strategy.", "interfaz pequeña.", "tests de comportamiento."],
        f"""```bash
mkdir -p {PROJ14}/src {PROJ14}/adr
```
Implementa `CalculoPrecio` y al menos dos estrategias (tarifa base, promo 10%). Vitest: caso normal y promo.
ADR `001-strategy-precio.md`: contexto, decisión, **cuándo NO** usar Strategy aquí.""",
        [("Refactoring.Guru", "Strategy", "GoF creacionales intro")],
        ["Strategy con ≥2 tests verdes.", "ADR 001 commiteado.", "README enlaza archivo."],
        ["Clase Strategy vacía.", "Tests que mockean todo."],
    ),
    _lesson(
        "Factory Method para notificadores de canal",
        1,
        "Refactoring.Guru Factory Method",
        f"{PROJ14}/src/notificador-factory.ts",
        "Encapsular creación de notificadores (email vs enlace WhatsApp) con Factory Method o factory simple en TS.",
        "Agenda Ops enviará recordatorios por distintos canales sin que el dominio conozca detalles.",
        ["Factory Method.", "creación variable.", "dominio aislado."],
        f"Crea interfaz `Notificador` y factory `crearNotificador(canal)`. Test: factory devuelve implementación correcta por canal.",
        [("Refactoring.Guru", "Factory Method", "—")],
        ["Factory con test por canal.", "Sin `new` disperso en servicio de citas.", "Commit feat(m14)."],
        ["Factory que solo hace `new` fijo.", "Lógica de negocio dentro del factory."],
    ),
    _lesson(
        "Singleton: cuándo NO usarlo",
        1,
        "GoF Singleton + notas anti-patrón",
        f"{PROJ14}/adr/002-singleton-rechazado.md",
        "Documentar por qué **no** usar Singleton para DB/logger global en Agenda Ops y qué alternativa (DI) usarás en M17.",
        "Singleton en tests y multi-tenant es deuda; mejor inyectar dependencias.",
        ["Singleton.", "estado global.", "inyección de dependencias."],
        f"Escribe ADR 002: caso rechazado (p. ej. conexión DB). Lista 3 problemas (tests, tenant, concurrencia). Sin implementar Singleton productivo.",
        [("Refactoring.Guru", "Singleton", "Ficha M14 semana 1")],
        ["ADR 002 con alternativa DI.", "Enlazado desde README.", "Commit docs(m14)."],
        ["Implementar Singleton “porque GoF”.", "ADR sin consecuencias."],
    ),
    _lesson(
        "Cierre semana 1 — creacionales y bitácora",
        1,
        "Repaso creacionales + ficha M14",
        f"{PROJ14}/semana-01.md",
        "Cerrar semana 1: índice de patrones creacionales usados/rechazados y retro de un anti-patrón que evitaste.",
        "La bitácora evita repetir debates de diseño en M17.",
        ["bitácora.", "trazabilidad.", "anti-patrón."],
        f"`semana-01.md`: patrones tocados, commits (`git log --oneline`), qué integrarás al piloto.",
        [("Ficha", "../M14-patrones.md", "m13-diseno")],
        ["semana-01.md existe.", "Strategy+Factory referenciados.", "Retro honesta."],
        ["Semana sin commits.", "Mezclar patrones sin ADR."],
    ),
    _lesson(
        "Adapter para API de calendario externo",
        2,
        "Refactoring.Guru Adapter",
        f"{PROJ14}/src/calendario-adapter.ts",
        "Adaptar una interfaz ficticia de calendario externo a tu puerto de dominio `CalendarioPuerto`.",
        "Integraciones reales (Google Calendar luego) exigen Adapter, no ifs en el servicio de citas.",
        ["Adapter.", "puerto.", "librería terceros."],
        "Define puerto dominio + adapter que traduce tipos/fechas. Test: el dominio solo ve tu interfaz.",
        [("Refactoring.Guru", "Adapter", "—")],
        ["Adapter + test de traducción.", "Dominio sin import de SDK.", "ADR o nota en README."],
        ["Copiar tipos del SDK al dominio.", "Adapter que re-lanza errores crudos."],
    ),
    _lesson(
        "Decorator para logging de operaciones de cita",
        2,
        "Refactoring.Guru Decorator",
        f"{PROJ14}/src/cita-logging-decorator.ts",
        "Envolver un servicio de citas con Decorator que registre operaciones sin modificar la clase core.",
        "Observabilidad sin ensuciar reglas de negocio.",
        ["Decorator.", "composición.", "logging estructurado."],
        "Implementa decorador que loguea `crear`/`cancelar` (sin PII en prod — documenta qué omites). Test: core se invoca.",
        [("Refactoring.Guru", "Decorator", "—")],
        ["Decorator con test.", "PII no en logs de ejemplo.", "Commit."],
        ["Decorator que cambia comportamiento.", "Logs con teléfono completo."],
    ),
    _lesson(
        "Facade para el flujo agendar cita",
        2,
        "Refactoring.Guru Facade",
        f"{PROJ14}/src/agendar-cita-facade.ts",
        "Crear Facade `agendarCita` que coordine validación, persistencia (fake) y evento.",
        "El panel y la API de M17 necesitan un punto de entrada claro, no seis llamadas sueltas.",
        ["Facade.", "orquestación.", "caso de uso."],
        "Facade con dependencias inyectadas (repos fake). Test happy path y error de solapamiento.",
        [("m13-diseno", "secuencia crear cita", "—")],
        ["Facade + 2 tests.", "Alineado a caso de uso M13.", "Nota en README."],
        ["Facade con SQL dentro.", "Sin test de error."],
    ),
    _lesson(
        "Tests de regresión en API pública del módulo",
        2,
        "Código limpio cap. pruebas (selecto)",
        f"{PROJ14}/tests/regresion-publica.test.ts",
        "Añadir tests que solo usen la API pública de tus patrones de la semana 2 (sin acoplarse a internals).",
        "M15 exigirá lo mismo en el piloto; hoy practicas el hábito.",
        ["API pública.", "regresión.", "encapsulamiento."],
        "≥3 tests que fallen si cambias detalle interno pero mantienes contrato. Documenta qué es público.",
        [("Ficha", "../M15-vv-calidad.md", "Vitest")],
        ["Suite regresión verde.", "Lista API pública en README.", "Cierre semana 2."],
        ["Tests de campos privados.", "Romper tests al refactor legítimo."],
    ),
    _lesson(
        "Observer para eventos de dominio",
        3,
        "Refactoring.Guru Observer",
        f"{PROJ14}/src/eventos-cita-observer.ts",
        "Publicar evento `CitaCreada` y suscriptores (auditoría, recordatorio futuro) con Observer.",
        "Desacopla efectos secundarios del agregado cita.",
        ["Observer.", "evento dominio.", "suscriptor."],
        "Implementa bus simple o lista de handlers. Test: al crear cita se notifica a N suscriptores.",
        [("Refactoring.Guru", "Observer", "—")],
        ["Observer con ≥2 suscriptores en test.", "ADR 003 o sección README.", "Commit."],
        ["Observer con orden frágil no documentado.", "Lógica de negocio en suscriptor."],
    ),
    _lesson(
        "Command para acciones admin reversibles",
        3,
        "Refactoring.Guru Command (selecto)",
        f"{PROJ14}/src/admin-command.ts",
        "Modelar una acción admin (p. ej. cancelar cita masiva) como Command con `ejecutar`/`deshacer` opcional.",
        "Panel owner en Agenda Ops puede necesitar deshacer errores humanos.",
        ["Command.", "undo.", "invoker."],
        "Un command con undo en memoria. Test ejecutar + deshacer restaura estado.",
        [("Refactoring.Guru", "Command", "—")],
        ["Command con test undo.", "Sin mezclar con HTTP.", "Nota límites (no transaccional DB aún)."],
        ["Command gigante con todo el CRUD.", "Undo sin prueba."],
    ),
    _lesson(
        "Cierre P1 — Strategy, Observer y Factory",
        3,
        "Ficha M14 P1",
        f"{PROJ14}/README.md índice P1",
        "Verificar P1: Strategy, Observer y Factory con tests y ADRs enlazados.",
        "P1 es prerequisito del proyecto ≥5 patrones.",
        ["P1.", "evidencia.", "índice."],
        "Actualiza README: tabla patrón → archivo → ADR. Checklist P1 en bitácora.",
        [("Ficha", "../M14-patrones.md", "—")],
        ["P1 ítems verificables.", "Tests verdes.", "README índice."],
        ["Marcar P1 sin tests.", "Factory sin uso real."],
    ),
    _lesson(
        "Repaso comportamiento y anti-patrón propio",
        3,
        "Retro patrones semana 3",
        f"{PROJ14}/semana-03.md",
        "Documentar un anti-patrón que cometiste y cómo lo corregiste (cargo cult).",
        "La retro alimenta code review en M15.",
        ["cargo cult.", "retro.", "simplificación."],
        "`semana-03.md` + enlace al commit de fix.",
        [("Refactoring.Guru", "catálogo", "—")],
        ["Anti-patrón descrito.", "Fix commiteado.", "Cierre semana 3."],
        ["Retro vacía.", "Añadir patrón sin necesidad."],
    ),
    _lesson(
        "Repository — interfaz Cita sin SQL",
        4,
        "Patrón Repository + diseño M13",
        f"{PROJ14}/src/cita-repository.ts",
        "Definir `CitaRepository` en dominio e implementación en memoria para tests.",
        "M17 usará Postgres; hoy fijas el puerto.",
        ["Repository.", "puerto.", "infra separada."],
        "Interfaz async `findById`, `save`. Impl memoria + test roundtrip.",
        [("m13-diseno", "persistencia ADR", "M09 esquema")],
        ["Interfaz en dominio.", "Impl memoria testeada.", "Sin SQL en dominio."],
        ["Repository que devuelve rows SQL.", "Mezclar con Service aún."],
    ),
    _lesson(
        "Service — capa aplicación de citas",
        4,
        "Service layer + casos de uso",
        f"{PROJ14}/src/cita-service.ts",
        "Implementar `CitaService` que use Repository y publique eventos (Observer de L09).",
        "Orquesta reglas sin conocer HTTP ni SQL.",
        ["Service.", "caso de uso.", "transacción futura."],
        "Service crea cita con validación de horario. Test con repo memoria + fake event bus.",
        [("m13-diseno", "capas", "—")],
        ["Service con tests.", "Reglas no en controller.", "Enlace a Repository."],
        ["God service.", "Validación solo en front."],
    ),
    _lesson(
        "Refactor P3 — módulo legacy antes y después",
        4,
        "Refactoring Fowler (intro)",
        f"{PROJ14}/refactor-notas.md",
        "Refactorizar un módulo propio (spike previo o archivo `legacy-citas.ts`) sin cambiar comportamiento observable.",
        "P3 demuestra que entiendes patrones como herramienta, no decoración.",
        ["refactor seguro.", "tests antes.", "diff."],
        "Tests de caracterización → refactor → mismos tests verdes. `refactor-notas.md` con antes/después.",
        [("Ficha", "../M14-patrones.md", "P3")],
        ["refactor-notas.md.", "Tests verdes antes/después.", "Diff o commits."],
        ["Refactor sin tests.", "Cambiar comportamiento silencioso."],
    ),
    _lesson(
        "Cierre M14 — cinco patrones e integración M17",
        4,
        "Ficha M14 proyecto + M17 ficha",
        f"{PROJ14}/README.md proyecto + adr resumen",
        "Entregar índice ≥5 patrones justificados y plan de migración a `projects/m17-agenda-ops/`.",
        "El piloto hereda decisiones; hoy las dejas trazables.",
        ["handoff M17.", "ADR resumen.", "criterios dominio."],
        "README final: 5+ patrones, ADRs, comando test. `nota-handoff-m17.md` con rutas a copiar.",
        [("Ficha", "../M14-patrones.md", "../M17-aplicaciones-web.md")],
        ["≥5 patrones en índice.", "Handoff M17.", "Cierre M14 commit."],
        ["Patrones sin justificación.", "Olvidar tests."],
    ),
]

M15 = [
    _lesson(
        "Entorno M15 y pirámide de tests",
        1,
        "Código limpio cap. 9 + Vitest",
        f"{PROJ15}/piramide.md + tests iniciales",
        "Crear `projects/m15-calidad/`, documentar pirámide objetivo para Agenda Ops y 5 tests iniciales de dominio.",
        "Sin pirámide escrita, acabarás con E2E lentos o cero tests de auth.",
        ["pirámide.", "unit.", "regla negocio."],
        f"""```bash
mkdir -p {PROJ15}/tests
```
Elige función dominio (crear cita, solapamiento). 5 tests: feliz, regla rota, y placeholders auth si aplica.""",
        [("Vitest", "getting started", "Código limpio cap. 9")],
        ["piramide.md.", "5 tests.", "Commit test(m15)."],
        ["Solo tests felices.", "Pirámide genérica sin capas."],
    ),
    _lesson(
        "Tests unitarios puros de reglas de cita",
        1,
        "Dominio sin I/O",
        f"{PROJ15}/tests/dominio-citas.test.ts",
        "Ampliar tests unitarios: pasado, duración, solapamiento, zona horaria documentada.",
        "La lógica de citas es donde más duele un bug en producción.",
        ["unit puro.", "fast feedback.", "tabla casos."],
        "≥8 casos en tabla markdown + tests. Sin DB ni HTTP en esta lección.",
        [("m12-srs", "stories Must", "—")],
        ["≥8 tests dominio.", "Tabla casos.", "Verde local."],
        ["Tests que levantan servidor.", "Datos hardcode sin nombre."],
    ),
    _lesson(
        "Qué no testear y carpetas de coverage",
        1,
        "Vitest coverage v8",
        f"{PROJ15}/coverage-objetivo.md",
        "Definir carpetas donde coverage **sí** importa (`domain/`) y dónde no (DTOs boilerplate).",
        "100 % en mappers no salva un IDOR.",
        ["coverage útil.", "exclusiones.", "umbral."],
        "`coverage-objetivo.md` + script `npm test -- --coverage` si aplica al spike.",
        [("Vitest", "coverage", "Ficha M15")],
        ["Documento coverage.", "Umbral solo dominio.", "Commit."],
        ["Perseguir 100 % global.", "Ignorar dominio."],
    ),
    _lesson(
        "Cierre semana 1 — suite dominio y bitácora",
        1,
        "Repaso P1 parcial",
        f"{PROJ15}/semana-01.md",
        "Cerrar semana 1 con bitácora y verificación de que cada regla SRS Must tiene al menos un test.",
        "Trazabilidad SRS → test es contrato para M17.",
        ["trazabilidad.", "Must.", "bitácora."],
        "Matriz story/test en `semana-01.md`.",
        [("m12-srs", "srs-v1", "—")],
        ["Matriz story→test.", "Suite verde.", "Cierre semana 1."],
        ["Tests huérfanos.", "Sin enlace a SRS."],
    ),
    _lesson(
        "Fake repositorio y reloj para tests rápidos",
        2,
        "Test doubles — Fowler / Vitest mocks",
        f"{PROJ15}/tests/fakes/",
        "Implementar repo en memoria y `RelojFalso` para probar citas en el futuro/pasado.",
        "Tests de integración lentos matan CI; fakes bien hechos dan confianza.",
        ["fake.", "reloj.", "determinismo."],
        "Fakes en carpeta dedicada. Test que avanza reloj y verifica expiración o ventana.",
        [("Vitest", "mocking guide", "—")],
        ["Fakes reutilizables.", "Test reloj.", "Sin mock excesivo."],
        ["Mock de cada línea.", "Fake que no respeta contrato repo."],
    ),
    _lesson(
        "Tests de integración con persistencia",
        2,
        "Testcontainers o DB test (documentado)",
        f"{PROJ15}/tests/integration/",
        "Un test de integración que persista y lea una cita (sqlite test o docker postgres).",
        "M17 usará Postgres; hoy validas el puerto Repository real.",
        ["integración.", "migración.", "fixture."],
        "Documenta cómo levantar DB test en README. ≥1 test integración verde.",
        [("m09", "esquema citas", "m14 Repository")],
        ["Test integración.", "README comando.", "Limpieza datos test."],
        ["Usar prod DB.", "Tests orden-dependientes."],
    ),
    _lesson(
        "Tests HTTP de API — auth y validación",
        2,
        "supertest o fetch contra app test",
        f"{PROJ15}/tests/api/",
        "Tests HTTP: 401 sin sesión, 400 payload inválido, 201 feliz en ruta de citas (spike o m17).",
        "La autorización se prueba en servidor, no ocultando botones.",
        ["HTTP.", "401.", "400."],
        "≥4 tests API. Tabla entrada/esperado como en ficha M15.",
        [("OWASP", "Auth cheat sheet", "m13 endpoints")],
        ["401 automatizado.", "400 validación.", "201 feliz."],
        ["Solo test unitario.", "Olvidar 403."],
    ),
    _lesson(
        "IDOR y roles — casos 403",
        2,
        "Hilo seguridad + stories M12",
        f"{PROJ15}/tests/seguridad-idor.test.ts",
        "Añadir tests que demuestren 403 al acceder a cita de otro negocio o acción de owner como staff.",
        "IDOR en piloto destruye confianza del design partner.",
        ["IDOR.", "403.", "multi-negocio futuro."],
        "≥2 tests 403 documentados con usuario/rol en comentario del test.",
        [("Hilo", "seguridad.md", "m12 RNF")],
        ["403 reproducible.", "Documentado en piramide.md capa API.", "Commit."],
        ["403 manual solo.", "Mensaje que filtra datos."],
    ),
    _lesson(
        "Workflow GitHub Actions — esqueleto",
        3,
        "Actions quickstart",
        f"{PROJ15}/.github/workflows/ci.yml o raíz",
        "Crear workflow `ci.yml`: checkout, node 20, install, test.",
        "CI obligatoria es práctica P2 y base de M17.",
        ["CI.", "workflow.", "push PR."],
        "Workflow mínimo verde en push. Documenta ruta en README M15.",
        [("GitHub", "Actions docs", "—")],
        ["Workflow existe.", "Verde en main o rama.", "README enlace."],
        ["CI solo local.", "Sin pin de node."],
    ),
    _lesson(
        "Lint y formato en pipeline",
        3,
        "ESLint + Prettier del stack",
        "ci.yml lint step",
        "Añadir paso `npm run lint` (o equivalente) que falle CI si hay errores.",
        "Estilo consistente reduce ruido en review.",
        ["lint.", "format.", "fail fast."],
        "Configura lint en spike o enlaza monorepo. Paso en CI documentado.",
        [("Ficha", "../M15-vv-calidad.md", "—")],
        ["Lint en CI.", "Fix o suppress justificado.", "Commit."],
        ["lint --fix en CI sin check.", "Desactivar reglas críticas."],
    ),
    _lesson(
        "npm audit y política de dependencias",
        3,
        "npm audit docs",
        "ci.yml audit step",
        "Añadir `npm audit --audit-level=high` (o documentar excepción con ticket).",
        "Supply chain importa aunque seas piloto.",
        ["audit.", "dependencias.", "CVE."],
        "Paso audit en CI. Si falla, `SECURITY-EXCEPTIONS.md` con razón y fecha revisión.",
        [("npm", "audit", "OWASP dep check")],
        ["Audit en CI.", "Política escrita.", "Verde o excepción documentada."],
        ["Ignorar audit.", "Excepciones sin fecha."],
    ),
    _lesson(
        "Badge README y artefacto de test",
        3,
        "README pipeline",
        f"{PROJ15}/README.md CI",
        "Enlazar workflow en README; opcional subir resumen de tests como artefacto.",
        "El design partner no ve tu CI; tu yo futuro sí necesita el enlace.",
        ["badge.", "documentación.", "onboarding."],
        "README: cómo correr tests local vs CI. Captura o enlace Actions.",
        [("GitHub", "badges", "—")],
        ["README actualizado.", "Enlace CI.", "Cierre semana 3 P2."],
        ["CI secreta.", "Sin instrucciones local."],
    ),
    _lesson(
        "Checklist de code review",
        4,
        "Checklist propio + seguridad",
        f"{PROJ15}/checklist-review.md",
        "Redactar checklist PR: estilo, tests, migraciones, secrets, auth, IDOR.",
        "P3 exige aplicarlo en un PR real o simulado.",
        ["review.", "checklist.", "seguridad."],
        "≥15 ítems verificables. Incluye “¿hay test de regresión?” y “¿validación server?”.",
        [("Hilo", "seguridad.md", "Código limpio")],
        ["checklist-review.md.", "Ítems seguridad.", "Commit."],
        ["Checklist vago.", "Sin ítems auth."],
    ),
    _lesson(
        "Review simulado en PR o notas",
        4,
        "Ejemplo review",
        f"{PROJ15}/review-ejemplo.md",
        "Aplicar checklist a un diff (PR propio o parche ficticio) con comentarios línea a línea.",
        "Practicar review enseña a escribir código revisable.",
        ["PR.", "comentarios.", "severidad."],
        "`review-ejemplo.md` con ≥10 comentarios categorizados (blocker/nit).",
        [("Ficha", "../M15-vv-calidad.md", "P3")],
        ["review-ejemplo.md.", "Checklist referenciado.", "Al menos 1 blocker encontrado."],
        ["Review de 2 líneas.", "Sin categoría."],
    ),
    _lesson(
        "Política bug → test el mismo día",
        4,
        "Regresión documentada",
        f"{PROJ15}/regresiones.md",
        "Documentar un bug real o simulado y el test añadido el mismo día.",
        "Esta regla separa equipos serios de demos frágiles.",
        ["regresión.", "política.", "postmortem ligero."],
        "Entrada en `regresiones.md`: síntoma, causa, test, commit hash.",
        [("Código limpio", "pruebas", "—")],
        ["regresiones.md con 1 caso.", "Test asociado.", "Commit."],
        ["Bug sin test.", "Solo fix manual."],
    ),
    _lesson(
        "Cierre M15 — pipeline, coverage dominio, dominio",
        4,
        "Ficha M15 criterios",
        f"{PROJ15}/nota-cierre-m15.md",
        "Auditar P1–P3, coverage en dominio, CI verde, criterios dominio respondidos.",
        "M17 debe mantener este pipeline; hoy lo dejas listo.",
        ["handoff M17.", "P1–P3.", "dominio."],
        "`nota-cierre-m15.md` + checklist ficha. Enlaza workflow y coverage report.",
        [("Ficha", "../M15-vv-calidad.md", "../M17-aplicaciones-web.md")],
        ["P1–P3 verificados.", "401/403 en tests.", "Cierre commit."],
        ["Marcar sin CI.", "Coverage solo en UI."],
    ),
]

M16 = [
    _lesson(
        "Recorrido persona nueva y fricciones día 1",
        1,
        "Krug cap. 1 + producto Agenda Ops",
        f"{PROJ16}/heuristicas/fricciones-dia1.md",
        "Recorrer UI/wireframe del piloto como usuario nuevo y listar ≥10 fricciones al agendar cita.",
        "Tu intuición de dev no es la del dueño del negocio.",
        ["fricción.", "tarea.", "design partner."],
        f"""```bash
mkdir -p {PROJ16}/heuristicas {PROJ16}/sesiones
```
Sin ayuda: crear cita. Anota cada pausa/confusión.""",
        [("Krug", "No me hagas pensar", "producto-saas.md")],
        ["≥10 fricciones.", "Fecha y contexto.", "Commit docs(m16)."],
        ["Lista genérica.", "Sin probar flujo real."],
    ),
    _lesson(
        "Auditoría Nielsen — tres heurísticas profundas",
        1,
        "10 heurísticas NN/g",
        f"{PROJ16}/heuristicas/auditoria-v0.md",
        "Aplicar al menos 3 heurísticas Nielsen con número, nombre y evidencia en captura o texto.",
        "Vocabulario común con stakeholders del piloto.",
        ["Nielsen.", "severidad.", "evidencia."],
        "Tabla hallazgo como en ficha M16. Enlaza a fricciones-dia1.",
        [("NN/g", "10 heuristics", "—")],
        ["auditoria-v0.md.", "≥3 heurísticas.", "Severidad asignada."],
        ["Heurística sin evidencia.", "Solo opinión."],
    ),
    _lesson(
        "Estados vacío, carga y error en agenda",
        1,
        "Krug formularios + estados UI",
        f"{PROJ16}/heuristicas/estados-ui.md",
        "Diseñar o auditar estados vacío/carga/error en lista de citas y formulario.",
        "Agenda vacía el primer día es normal; error de red no debe ser pantalla blanca.",
        ["empty state.", "loading.", "error recovery."],
        "Mockups o capturas en `estados-ui.md`. Propuesta de copy en español claro.",
        [("m17", "ui-estados futuro", "m12 stories")],
        ["3 estados documentados.", "Copy propuesto.", "Commit."],
        ["Spinner infinito.", "Error técnico crudo."],
    ),
    _lesson(
        "auditoria-v1 y cierre P1 heurísticas",
        1,
        "Ficha M16 P1",
        f"{PROJ16}/heuristicas/auditoria-v1.md",
        "Consolidar auditoría v1 con ≥10 hallazgos, severidad y fix propuesto.",
        "P1 alimenta iteración semana 3.",
        ["auditoría.", "prioridad.", "P1."],
        "Promueve v0 → v1. README enlaza auditoria-v1.",
        [("Ficha", "../M16-ihc.md", "—")],
        ["auditoria-v1.md.", "≥10 hallazgos.", "P1 listo."],
        ["Duplicar hallazgos.", "Sin fix propuesto."],
    ),
    _lesson(
        "Prototipo navegable y tareas del SRS",
        2,
        "Krug navegación",
        f"{PROJ16}/prototipo/",
        "Prototipo HTML/Figma con flujos Must: crear cliente, cita, ver agenda día.",
        "Test sin prototipo es teatro.",
        ["prototipo.", "Must.", "flujo."],
        "≥3 pantallas enlazadas. Lista tareas alineadas a `m12-srs`.",
        [("m12-srs", "Must", "—")],
        ["Prototipo navegable.", "Tareas escritas.", "Commit."],
        ["Solo mock estático suelto.", "Tareas fuera de SRS."],
    ),
    _lesson(
        "Guion de test de usabilidad 15–30 min",
        2,
        "NN/g usability test",
        f"{PROJ16}/sesiones/guion-v1.md",
        "Redactar guion con contexto, 3 tareas, preguntas cierre y consentimiento básico.",
        "Guion fijo hace comparables las 5 sesiones.",
        ["guion.", "consentimiento.", "think aloud."],
        "Plantilla participante anónimo. No pidas datos sensibles innecesarios.",
        [("NN/g", "running a test", "—")],
        ["guion-v1.md.", "Consentimiento.", "3 tareas medibles."],
        ["Guion que guía al usuario.", "Sin tiempo por tarea."],
    ),
    _lesson(
        "Sesiones 1–3 — notas de participantes",
        2,
        "Facilitación test",
        f"{PROJ16}/sesiones/participante-*.md",
        "Facilitar 3 sesiones (reales o design partners) y capturar notas estructuradas.",
        "Tres sesiones ya muestran patrones repetidos.",
        ["sesión.", "patrón.", "cita textual."],
        "≥3 archivos `participante-N.md` con tarea, éxito/fallo, quotes.",
        [("Krug", "test de pasillo", "—")],
        ["3 sesiones documentadas.", "Sin PII innecesaria.", "Commits."],
        ["Resumir sin datos.", "Defender el diseño."],
    ),
    _lesson(
        "Sesiones 4–5 y resumen agregado P2",
        2,
        "Síntesis cualitativa",
        f"{PROJ16}/sesiones/resumen-5-usuarios.md",
        "Completar 5 sesiones y sintetizar patrones (impacto × frecuencia).",
        "P2 cierra con evidencia agregada, no anécdotas.",
        ["síntesis.", "patrón.", "P2."],
        "resumen-5-usuarios.md con top problemas y citas representativas.",
        [("Ficha", "../M16-ihc.md", "P2")],
        ["5 sesiones.", "Resumen agregado.", "P2 verificable."],
        ["Cinco amigos sin tareas.", "Un solo párrafo."],
    ),
    _lesson(
        "Priorizar top 5 hallazgos",
        3,
        "Matriz impacto esfuerzo",
        f"{PROJ16}/iteracion/prioridad.md",
        "Elegir 5 hallazgos a abordar antes de M17 con prioridad y owner (tú).",
        "No puedes arreglar todo; prioriza lo que bloquea el piloto.",
        ["priorización.", "impacto.", "MVP UX."],
        "Matriz + enlace a sesiones/heurísticas.",
        [("Informe", "borrador", "—")],
        ["prioridad.md top 5.", "Al menos 1 severidad alta.", "Commit."],
        ["Priorizar por gusto.", "Ignorar seguridad UX."],
    ),
    _lesson(
        "Iteración UI — antes y después",
        3,
        "Fix implementado o wireframe",
        f"{PROJ16}/iteracion/",
        "Implementar o wireframear fixes del top 5; capturas antes/después.",
        "P3 exige evidencia visual del cambio.",
        ["iteración.", "antes/después.", "P3."],
        "Carpeta `iteracion/` con pares de capturas o diff front.",
        [("m17", "handoff UX", "—")],
        ["≥3 fixes visibles.", "Antes/después.", "Commit si hay código."],
        ["Solo texto “lo haré”.", "Mensajes error verbosos."],
    ),
    _lesson(
        "Informe de usabilidad para stakeholders",
        3,
        "Informe ejecutivo 1 página",
        f"{PROJ16}/informe-usabilidad.md",
        "Redactar informe: método, participantes, hallazgos, cambios, riesgos UX→seguridad.",
        "El design partner lee esto, no tu bitácora cruda.",
        ["informe.", "ejecutivo.", "stakeholder."],
        "1 página resumen + anexo método. Enlaza artefactos M16.",
        [("Ficha", "../M16-ihc.md", "proyecto")],
        ["informe-usabilidad.md.", "Resumen 1 pág.", "Riesgos seguridad UX."],
        ["Informe sin cambios concretos.", "IDs internos en errores."],
    ),
    _lesson(
        "Cierre M16 — handoff M17 y criterios dominio",
        3,
        "Ficha M16 cierre",
        f"{PROJ16}/nota-handoff-m17-ux.md",
        "Cerrar M16: checklist P1–P3, guion reutilizable, lista cambios para M17.",
        "M17 implementa; M16 ya decidió qué duele al usuario.",
        ["handoff.", "guion.", "dominio UX."],
        "`nota-handoff-m17-ux.md` + README índice. Responde criterios dominio en bitácora.",
        [("Ficha", "../M16-ihc.md", "../M17-aplicaciones-web.md")],
        ["Handoff M17.", "P1–P3 ok.", "Cierre commit."],
        ["Saltar iteración.", "Informe sin método."],
    ),
]

# M17 — 8 semanas × 4 lecciones (alta profundidad Agenda Ops MVP)
def m17_lessons() -> list[dict]:
    w = _lesson
    return [
        w(
            "Scaffold Agenda Ops — API, DB y stack.md",
            1,
            "producto-saas.md + m13-diseno + M09 esquema",
            f"{PROJ17}/stack.md + scaffold API",
            "Inicializar `projects/m17-agenda-ops/` con TypeScript strict, conexión Postgres y documentar stack fijo.",
            "Cambiar stack a mitad de materia sin ADR destruye velocidad.",
            ["scaffold.", "Postgres.", "monolito modular."],
            f"""```bash
mkdir -p {PROJ17}/docs {PROJ17}/src
```
Crea `stack.md` (framework HTTP, ORM, front). Migra o enlaza esquema M09. Health `GET /health` 200.""",
            [("m13-diseno", "endpoints.md", "m09 esquema")],
            ["Repo scaffold.", "stack.md.", "DB conecta local.", "Health check."],
            ["Stack sin documentar.", "Secrets en repo."],
        ),
        w(
            "Registro con hash de contraseña",
            1,
            "OWASP Password Storage + bcrypt/argon2",
            "POST /auth/register",
            "Implementar registro: validar email/password, hash fuerte, persistir usuario ligado al negocio piloto.",
            "Auth real desde el MVP — no usuarios en texto plano.",
            ["hash.", "registro.", "validación."],
            "Zod (o similar) en body. Test integración 201 y 400 email inválido.",
            [("OWASP", "Password Storage", "m13 ADR auth")],
            ["Register funciona.", "Hash no reversible.", "Test 400."],
            ["MD5.", "Password en logs."],
        ),
        w(
            "Login, sesión y GET /me protegido",
            1,
            "MDN cookies + ADR sesión M13",
            "POST /auth/login + GET /me",
            "Login con cookie HttpOnly o JWT en cookie; `GET /me` devuelve 401 sin credencial.",
            "El panel Agenda Ops necesita identidad servidor-confiable.",
            ["sesión.", "401.", "HttpOnly."],
            "Tests: login → me 200; sin cookie → 401. Documenta elección en `docs/auth.md`.",
            [("MDN", "HTTP cookies", "hilo seguridad")],
            ["Login+me.", "401 test.", "auth.md."],
            ["JWT localStorage sin doc.", "Me devuelve todo el row."],
        ),
        w(
            "Cierre semana 1 — suite auth P1",
            1,
            "Ficha M17 P1",
            f"{PROJ17}/tests/auth.test.ts",
            "Consolidar tests auth (register, login, me, logout) y marcar P1 parcial en README.",
            "P1 es puerta para todo CRUD.",
            ["P1.", "suite auth.", "logout."],
            "≥6 tests auth. README comando `npm test`. Commit cierre semana 1.",
            [("Ficha", "../M17-aplicaciones-web.md", "m15 CI")],
            ["Suite auth verde.", "Logout documentado.", "P1 parcial README."],
            ["Auth sin tests.", "Solo manual Postman."],
        ),
        w(
            "Modelo de dominio citas, clientes y servicios",
            2,
            "m13 diagrama clases + srs-v1",
            "migraciones / entidades",
            "Alinear tablas y entidades con diseño M13: citas, clientes, servicios, relaciones y reglas en código dominio.",
            "CRUD sin modelo coherente genera IDOR y datos huérfanos.",
            ["entidad.", "migración.", "dominio."],
            "Migraciones aplicadas. Tipos dominio sin dependencia de ORM en reglas puras (carpeta `domain/`).",
            [("m12-srs", "RF citas", "m13 clases")],
            ["Migraciones.", "domain/ con reglas.", "Commit."],
            ["Lógica solo en controllers.", "Sin FK."],
        ),
        w(
            "API citas — crear y listar con reglas",
            2,
            "REST + validación horarios",
            "POST/GET /citas",
            "Endpoints crear/listar citas con auth, validación fin>inicio, no pasado sin override documentado.",
            "Core del piloto Agenda Ops.",
            ["REST.", "409 solapamiento.", "paginación."],
            "Tests 201, 400 horario, 409 solapamiento. Listar con filtro fecha.",
            [("m12", "stories citas", "—")],
            ["POST/GET citas.", "Reglas testeadas.", "401 sin auth."],
            ["Listar sin auth.", "Timezone ignorada."],
        ),
        w(
            "CRUD clientes y servicios",
            2,
            "SRS RF clientes/servicios",
            "/clientes /servicios",
            "CRUD completo clientes y servicios con autorización owner/staff según matriz preliminar.",
            "Servicios definen duración y precio base para citas.",
            ["CRUD.", "servicio.", "cliente."],
            "Endpoints + tests feliz y 404. Seeds opcionales.",
            [("m12-srs", "Must", "m14 precio opcional")],
            ["CRUD ambos recursos.", "Tests.", "Commit."],
            ["Mezclar cliente entre negocios.", "Sin validación."],
        ),
        w(
            "Seeds demo y datos design partner",
            2,
            "Fixtures reproducibles",
            f"{PROJ17}/scripts/seed.ts",
            "Script seed con negocio piloto, owner, staff, citas ejemplo para demo.",
            "Demo reproducible evita ‘en mi máquina sí’.",
            ["seed.", "demo.", "idempotencia."],
            "seed documentado en README. No PII real del partner en repo.",
            [("README", "demo creds test", "—")],
            ["Seed corre.", "README creds test.", "Cierre semana 2."],
            ["Datos reales en git.", "Seed no repetible."],
        ),
        w(
            "Matriz de permisos owner y staff",
            3,
            "m13 casos de uso admin",
            f"{PROJ17}/docs/permisos.md",
            "Documentar tabla acción×rol (cancelar cita, ver reportes, gestionar staff).",
            "Roles sin matriz escrita se implementan inconsistente.",
            ["RBAC.", "owner.", "staff."],
            "permisos.md enlazado a endpoints. Cada ruta sensible tiene rol en comentario OpenAPI o tabla.",
            [("m12", "stories roles", "OWASP access control")],
            ["permisos.md.", "Cobertura endpoints.", "Commit."],
            ["Staff = owner.", "Matriz vacía."],
        ),
        w(
            "Middleware de autorización en API",
            3,
            "Middleware pattern",
            "authorize(role) middleware",
            "Middleware que verifica rol y negocio en cada handler sensible.",
            "403 debe ser imposible de evitar desde el front.",
            ["middleware.", "403.", "contexto usuario."],
            "Tests staff bloqueado en acción owner. Test 403 IDOR entre recursos.",
            [("m15", "tests seguridad", "—")],
            ["Middleware activo.", "403 tests.", "Sin lógica duplicada."],
            ["Check solo en UI.", "Hardcode user id."],
        ),
        w(
            "Panel admin mínimo — gestión staff",
            3,
            "UI admin sin adornos",
            "ruta /admin o equivalente",
            "Pantalla admin: listar staff, invitar o crear staff (según SRS), solo owner.",
            "El dueño del negocio administra su equipo aquí.",
            ["admin.", "invitación.", "UX claro."],
            "UI fea pero clara. Errores 403 visibles. Notas en `docs/ui-admin.md`.",
            [("m16", "handoff UX", "—")],
            ["Admin usable.", "Owner-only verificado.", "ui-admin.md."],
            ["Admin sin auth.", "Confundir roles."],
        ),
        w(
            "Demo roles y inicio P3 WhatsApp",
            3,
            "Ficha P3 parcial",
            f"{PROJ17}/docs/demo-roles.md",
            "Grabar o documentar pasos demo: owner vs staff en acción bloqueada.",
            "P3 requiere evidencia reproducible para el design partner.",
            ["demo.", "roles.", "evidencia."],
            "demo-roles.md con usuarios test y pasos. Enlace a tests 403.",
            [("Ficha", "../M17-aplicaciones-web.md", "—")],
            ["demo-roles.md.", "Staff bloqueado demo.", "Cierre semana 3."],
            ["Demo sin script.", "Cuentas prod."],
        ),
        w(
            "Scaffold front y rutas protegidas",
            4,
            "React Router / framework docs",
            "front app + router",
            "Crear front con login, layout panel, rutas protegidas redirect a login.",
            "Agenda Ops se usa desde navegador diario.",
            ["SPA.", "protected route.", "layout."],
            "Estructura `apps/web` o `client/`. Env API_URL documentado.",
            [("MDN", "fetch", "m16 prototipo")],
            ["Front arranca.", "Redirect sin sesión.", "Commit."],
            ["CORS `*` sin doc.", "API_URL hardcode prod."],
        ),
        w(
            "Flujo login/logout en UI",
            4,
            "Forms accesibles",
            "páginas login",
            "Form login con labels, errores de credencial, logout que limpia sesión.",
            "Primera impresión del piloto.",
            ["login UI.", "error auth.", "logout."],
            "Manejo 401 en login. Test e2e opcional o checklist manual en docs.",
            [("m16", "estados error", "—")],
            ["Login/logout.", "Errores visibles.", "Sin password en state."],
            ["Alert genérico.", "Token en querystring."],
        ),
        w(
            "Listas con loading, error y vacío",
            4,
            "m16 estados-ui",
            f"{PROJ17}/docs/ui-estados.md",
            "Implementar agenda del día y listas con tres estados UX obligatorios.",
            "P2 exige documentación de estados.",
            ["loading.", "empty.", "error boundary."],
            "ui-estados.md con capturas o descripción por pantalla.",
            [("Ficha", "../M17-aplicaciones-web.md", "P2")],
            ["ui-estados.md.", "3 estados en UI.", "Commit."],
            ["Spinner eterno.", "Lista vacía sin CTA."],
        ),
        w(
            "Formularios citas y clientes accesibles",
            4,
            "MDN forms a11y básica",
            "formularios create",
            "Crear/editar cita y cliente con validación inline alineada a API.",
            "Errores server mapeados a campos.",
            ["form.", "a11y.", "validación."],
            "Labels, `aria-invalid`, mensajes en español. Commit cierre semana 4 P2 parcial.",
            [("MDN", "formularios", "m12 criterios")],
            ["Forms create/edit.", "Errores campo.", "P2 parcial."],
            ["Solo placeholder.", "Confiar solo client validation."],
        ),
        w(
            "Deep links WhatsApp — diseño del mensaje",
            5,
            "Docs proveedor WhatsApp",
            f"{PROJ17}/docs/integracion-whatsapp.md",
            "Definir plantilla mensaje recordatorio/confirmación con placeholders y enlace wa.me.",
            "Canal que el design partner ya usa.",
            ["deep link.", "plantilla.", "PII mínima."],
            "integracion-whatsapp.md: ejemplo URL encoded, qué datos van (nombre cita, hora).",
            [("Oficial", "WhatsApp Business", "—")],
            ["Doc plantilla.", "Sin secrets.", "Commit."],
            ["API keys en front.", "Teléfono en logs."],
        ),
        w(
            "Botón enviar recordatorio desde ficha cita",
            5,
            "UI + API log",
            "acción recordatorio",
            "En UI de cita, acción que abre WhatsApp o registra intento según diseño.",
            "Cierra loop operativo del negocio.",
            ["acción usuario.", "auditoría ligera.", "opt-in."],
            "Implementación + test manual documentado. Log sin PII completa.",
            [("m14", "notificador", "—")],
            ["Acción en UI.", "Log sanitizado.", "Test manual pasos."],
            ["Spam sin confirmación.", "Log con teléfono."],
        ),
        w(
            "Confirmación de cita y estados",
            5,
            "Flujo estado cita",
            "campo estado + UI",
            "Estados confirmada/pendiente/cancelada visibles y coherentes API↔UI.",
            "Staff y owner deben ver el mismo estado.",
            ["estado.", "sincronización.", "cancelación."],
            "Tests API cambio estado + UI refleja. Mensaje WhatsApp opcional al confirmar.",
            [("m12-srs", "flujos", "—")],
            ["Estados en API/UI.", "Tests.", "Commit."],
            ["Estado solo en front.", "Cancelar sin auth."],
        ),
        w(
            "Cierre P3 integración WhatsApp",
            5,
            "Ficha P3",
            "integracion-whatsapp.md completo",
            "Completar doc P3: capturas, límites legales/opt-in, qué no hace la integración.",
            "P3 no sustituye API oficial si no está configurada — documenta gaps.",
            ["P3.", "opt-in.", "gap."],
            "Checklist P3 en README. Cierre semana 5.",
            [("Ficha", "../M17-aplicaciones-web.md", "—")],
            ["P3 checklist.", "Capturas.", "Gaps honestos."],
            ["Prometer API sin credencial.", "Sin opt-in."],
        ),
        w(
            "Variables de entorno y secrets",
            6,
            "12-factor config",
            f"{PROJ17}/.env.example",
            "Separar config: DATABASE_URL, SESSION_SECRET, etc. `.env.example` sin valores reales.",
            "Deploy seguro empieza por no commitear secrets.",
            ["env.", "secrets.", "example."],
            "Validar arranque si falta variable crítica. Documentar en README.",
            [("OWASP", "Secrets management", "—")],
            [".env.example.", "Validación arranque.", "Commit."],
            [".env en git.", "Secrets en front."],
        ),
        w(
            "Deploy staging en PaaS",
            6,
            "Docs PaaS elegido",
            "URL staging",
            "Desplegar API+front o API primero en staging con build reproducible.",
            "Piloto invisible no es piloto.",
            ["deploy.", "staging.", "build."],
            "URL en README. Proceso `docs/deploy.md` paso a paso.",
            [("PaaS", "docs", "m19 preview")],
            ["Staging URL.", "deploy.md.", "Build CI opcional."],
            ["Deploy manual sin doc.", "Solo localhost."],
        ),
        w(
            "HTTPS y health checks",
            6,
            "TLS Let's Encrypt / proveedor",
            "HTTPS + /health",
            "Forzar HTTPS en prod/staging y health check para monitor.",
            "Design partner no debe ver “no seguro”.",
            ["TLS.", "HSTS.", "health."],
            "Verificar certificado válido. Health usado en deploy script.",
            [("MDN", "HTTPS", "—")],
            ["HTTPS activo.", "Health remoto.", "Commit."],
            ["HTTP prod.", "Health sin DB check documentado."],
        ),
        w(
            "Smoke test post-deploy",
            6,
            "Checklist smoke",
            f"{PROJ17}/docs/smoke-test.md",
            "Script o checklist: register/login/crear cita en staging.",
            "Detecta config rota antes de la demo.",
            ["smoke.", "staging.", "regresión manual."],
            "smoke-test.md con resultado fechado de última corrida.",
            [("m15", "regresión", "—")],
            ["smoke-test.md.", "Corrida fechada.", "Cierre semana 6."],
            ["Smoke solo health.", "Olvidar auth."],
        ),
        w(
            "Mapa OWASP Top 10 en el piloto",
            7,
            "OWASP Top 10 overview",
            f"{PROJ17}/docs/owasp-mapa.md",
            "Tabla: cada riesgo → mitigación actual o gap hacia M18.",
            "M18 profundiza; hoy ubicas huecos.",
            ["OWASP.", "gap.", "mitigación."],
            "owasp-mapa.md con ≥8 filas honestas.",
            [("OWASP", "Top 10", "hilo seguridad")],
            ["owasp-mapa.md.", "Gaps M18.", "Commit."],
            ["Marcar todo mitigado.", "Ignorar auth."],
        ),
        w(
            "Headers de seguridad y CORS prod",
            7,
            "MDN security headers",
            "helmet o equivalente",
            "Configurar headers básicos y CORS restrictivo a dominio front.",
            "Reduce superficie antes de abrir al partner.",
            ["helmet.", "CORS.", "CSP intro."],
            "Documenta valores en `docs/seguridad-http.md`. Test manual headers.",
            [("MDN", "CORS", "m10 lecciones")],
            ["Headers activos prod.", "CORS no `*`.", "Doc."],
            ["CORS abierto.", "CSP rota sin probar."],
        ),
        w(
            "Rate limit en login",
            7,
            "OWASP brute force",
            "rate limit middleware",
            "Limitar intentos login por IP/usuario con respuesta 429 documentada.",
            "Piloto público en internet necesita mínimo anti-fuerza bruta.",
            ["rate limit.", "429.", "login."],
            "Test 429 tras N intentos. No bloquear CI IPs — config test.",
            [("OWASP", "Authentication", "—")],
            ["Rate limit.", "429 test o manual.", "Commit."],
            ["Sin límite.", "Lockout permanente sin doc."],
        ),
        w(
            "Tests auth en CI o script local reproducible",
            7,
            "m15 pipeline",
            ".github/workflows en m17",
            "Asegurar que suite auth+roles corre en CI o script documentado `npm run test:ci`.",
            "Deploy sin tests es regresión garantizada.",
            ["CI.", "regresión.", "auth tests."],
            "Enlaza workflow desde README m17. Verde en main.",
            [("m15", "nota cierre", "—")],
            ["CI verde.", "Auth en pipeline.", "Cierre semana 7."],
            ["Tests skipped en CI.", "Solo local."],
        ),
        w(
            "ADR tenant_id y modelo multi-negocio",
            8,
            "producto-saas multi-tenant",
            f"{PROJ17}/docs/adr-tenant-id.md",
            "ADR: dónde va `tenant_id`/`negocio_id`, migración futura, queries siempre filtradas.",
            "M26 depende de esta decisión; M17 la prepara.",
            ["tenant_id.", "ADR.", "single-tenant piloto."],
            "ADR con contexto M09/M13. Lista tablas afectadas.",
            [("producto-saas.md", "fases", "m13 L15")],
            ["adr-tenant-id.md.", "Tablas listadas.", "Commit."],
            ["Multi-tenant completo día 1.", "Sin filtro en queries."],
        ),
        w(
            "Checklist camino a SaaS",
            8,
            "Ficha M17 checklist",
            f"{PROJ17}/docs/checklist-saas.md",
            "Completar checklist ficha: tablas, roles, HTTPS, tests — gaps honestos.",
            "Transparencia > checkboxes mentirosos.",
            ["checklist.", "gap.", "SaaS."],
            "checklist-saas.md copiado de ficha con Sí/No/Parcial.",
            [("Ficha", "../M17-aplicaciones-web.md", "—")],
            ["checklist-saas.md.", "Gaps con plan.", "Commit."],
            ["Todo Sí falso.", "Sin fecha para gaps."],
        ),
        w(
            "Demo grabable para design partner",
            8,
            "Guion demo 10 min",
            f"{PROJ17}/docs/demo-script.md",
            "Guion demo: onboarding, cita, WhatsApp, roles. URL staging y creds test.",
            "Validación real del MVP.",
            ["demo.", "partner.", "staging."],
            "demo-script.md + video opcional o capturas secuenciales.",
            [("m12", "design partner", "—")],
            ["demo-script.md.", "URL HTTPS.", "Credenciales test only."],
            ["Demo en localhost.", "Datos partner real."],
        ),
        w(
            "Cierre M17 — evidencias, dominio y handoff M19",
            8,
            "Ficha M17 criterios dominio",
            f"{PROJ17}/docs/nota-cierre-m17.md",
            "Auditar P1–P3, proyecto piloto, criterios dominio, README final y handoff deploy M19.",
            "Cierras la materia más densa del plan disciplinario.",
            ["cierre.", "handoff M19.", "dominio."],
            "nota-cierre-m17.md. README con URLs, tests, ADR, checklist. Commit `docs(m17): cierre materia`.",
            [("Ficha", "../M17-aplicaciones-web.md", "../M19-nube-devops.md")],
            ["P1–P3 verificados.", "HTTPS demo.", "Criterios dominio.", "Handoff M19."],
            ["Marcar completo sin deploy.", "Auth solo front."],
        ),
    ]


def main() -> None:
    counts = {
        "M14": write_materia("M14", M14),
        "M15": write_materia("M15", M15),
        "M16": write_materia("M16", M16),
        "M17": write_materia("M17", m17_lessons()),
    }
    print("Generated:", counts, "total:", sum(counts.values()))


if __name__ == "__main__":
    main()
